//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace BuenaVista.Module.BusinessObjects.BuenaVista
{

    public partial class Empleados : XPObject
    {
        int fIdPlanilla;
        public int IdPlanilla
        {
            get { return fIdPlanilla; }
            set { SetPropertyValue<int>(nameof(IdPlanilla), ref fIdPlanilla, value); }
        }
        string fNombre;
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        DateTime fFechaNacimiento;
        public DateTime FechaNacimiento
        {
            get { return fFechaNacimiento; }
            set { SetPropertyValue<DateTime>(nameof(FechaNacimiento), ref fFechaNacimiento, value); }
        }
        string fPuesto;
        public string Puesto
        {
            get { return fPuesto; }
            set { SetPropertyValue<string>(nameof(Puesto), ref fPuesto, value); }
        }
        bool fEstadoUsuario;
        public bool EstadoUsuario
        {
            get { return fEstadoUsuario; }
            set { SetPropertyValue<bool>(nameof(EstadoUsuario), ref fEstadoUsuario, value); }
        }
        bool fTieneAfp;
        public bool TieneAfp
        {
            get { return fTieneAfp; }
            set { SetPropertyValue<bool>(nameof(TieneAfp), ref fTieneAfp, value); }
        }
        bool fTieneIsss;
        public bool TieneIsss
        {
            get { return fTieneIsss; }
            set { SetPropertyValue<bool>(nameof(TieneIsss), ref fTieneIsss, value); }
        }
        bool fTieneRenta;
        public bool TieneRenta
        {
            get { return fTieneRenta; }
            set { SetPropertyValue<bool>(nameof(TieneRenta), ref fTieneRenta, value); }
        }
    }

}
