//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace BuenaVista.Module.BusinessObjects.BuenaVista
{

    public partial class Planillas : XPObject
    {
        DateTime fFechaInicio;
        public DateTime FechaInicio
        {
            get { return fFechaInicio; }
            set { SetPropertyValue<DateTime>(nameof(FechaInicio), ref fFechaInicio, value); }
        }
        DateTime fFechaFin;
        public DateTime FechaFin
        {
            get { return fFechaFin; }
            set { SetPropertyValue<DateTime>(nameof(FechaFin), ref fFechaFin, value); }
        }
        decimal fIsss;
        public decimal Isss
        {
            get { return fIsss; }
            set { SetPropertyValue<decimal>(nameof(Isss), ref fIsss, value); }
        }
        decimal fAfp;
        public decimal Afp
        {
            get { return fAfp; }
            set { SetPropertyValue<decimal>(nameof(Afp), ref fAfp, value); }
        }
        decimal fRenta;
        public decimal Renta
        {
            get { return fRenta; }
            set { SetPropertyValue<decimal>(nameof(Renta), ref fRenta, value); }
        }
        decimal fOtrosIngresos;
        public decimal OtrosIngresos
        {
            get { return fOtrosIngresos; }
            set { SetPropertyValue<decimal>(nameof(OtrosIngresos), ref fOtrosIngresos, value); }
        }
        decimal fDescuentos;
        public decimal Descuentos
        {
            get { return fDescuentos; }
            set { SetPropertyValue<decimal>(nameof(Descuentos), ref fDescuentos, value); }
        }
        decimal fHorasExtra;
        public decimal HorasExtra
        {
            get { return fHorasExtra; }
            set { SetPropertyValue<decimal>(nameof(HorasExtra), ref fHorasExtra, value); }
        }
        decimal fSalarioBase;
        public decimal SalarioBase
        {
            get { return fSalarioBase; }
            set { SetPropertyValue<decimal>(nameof(SalarioBase), ref fSalarioBase, value); }
        }
        decimal fPagoFinal;
        public decimal PagoFinal
        {
            get { return fPagoFinal; }
            set { SetPropertyValue<decimal>(nameof(PagoFinal), ref fPagoFinal, value); }
        }
        Empleados fEmpleado;
        [Association(@"PlanillasReferencesEmpleados")]
        public Empleados Empleado
        {
            get { return fEmpleado; }
            set { SetPropertyValue<Empleados>(nameof(Empleado), ref fEmpleado, value); }
        }
    }

}
