//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace BuenaVista.Module.BusinessObjects.BuenaVista
{

    public partial class RendimientoDiario : XPObject
    {
        Empleados fEmpleado;
        [Association(@"RendimientoDiarioReferencesEmpleados")]
        public Empleados Empleado
        {
            get { return fEmpleado; }
            set { SetPropertyValue<Empleados>(nameof(Empleado), ref fEmpleado, value); }
        }
        int fOrdenesAtendidas;
        public int OrdenesAtendidas
        {
            get { return fOrdenesAtendidas; }
            set { SetPropertyValue<int>(nameof(OrdenesAtendidas), ref fOrdenesAtendidas, value); }
        }
        decimal fPropina;
        public decimal Propina
        {
            get { return fPropina; }
            set { SetPropertyValue<decimal>(nameof(Propina), ref fPropina, value); }
        }
    }

}
