//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace BuenaVista.Module.BusinessObjects.BuenaVista
{

    public partial class Stock : XPObject
    {
        string fProducto;
        public string Producto
        {
            get { return fProducto; }
            set { SetPropertyValue<string>(nameof(Producto), ref fProducto, value); }
        }
        int fEntradas;
        public int Entradas
        {
            get { return fEntradas; }
            set { SetPropertyValue<int>(nameof(Entradas), ref fEntradas, value); }
        }
        int fSalidas;
        public int Salidas
        {
            get { return fSalidas; }
            set { SetPropertyValue<int>(nameof(Salidas), ref fSalidas, value); }
        }
        int fExistencias;
        public int Existencias
        {
            get { return fExistencias; }
            set { SetPropertyValue<int>(nameof(Existencias), ref fExistencias, value); }
        }
    }

}
